import { cardInterface } from '@app/models/cards.interface';

export let cardsBD: cardInterface[] = [
  {
    img: '/assets/images/cards/burguerChicken.jpg',
    existentes: 0,
    nombre: 'Burguer Chicken',
    REF: '#54m4652n1',
    precio: '$13.450',
    estrellas: 4,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/burguersPapas.jpg',
    existentes: 0,
    nombre: 'Doble carne y papas',
    REF: '#54m4652n2',
    precio: '$23.450',
    estrellas: 3,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/lunchPolloPapas.jpg',
    existentes: 0,
    nombre: 'Blunch Pollo Papas',
    REF: '#54m4652n3',
    precio: '$10.450',
    estrellas: 3,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/polloNaranja.png',
    existentes: 0,
    nombre: 'Pollo Naranja',
    REF: '#54m4652n4',
    precio: '$25.650',
    estrellas: 4,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/sachipapa1.png',
    existentes: 0,
    nombre: 'Sachipapa',
    REF: '#54m4652n5',
    precio: '$8.350',
    estrellas: 3,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/salchipapaCilantro.png',
    existentes: 0,
    nombre: 'Salchipapa Cilantro',
    REF: '#54m4652n6',
    precio: '$8.350',
    estrellas: 4,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/nuggetsPapas.jpg',
    existentes: 0,
    nombre: 'Nuggets Papas',
    REF: '#54m4652n7',
    precio: '$14.990',
    estrellas: 3,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  },
  {
    img: '/assets/images/cards/carneAsada.jpg',
    existentes: 0,
    nombre: 'Carne Asada',
    REF: '#54m4652n8',
    precio: '$28.790',
    estrellas: 5,
    peso: 'string',
    Ingredientes: 'string',
    incluye: 'string',
  }
];
