import { comboInterface } from '@app/models/combo.interface';

export let combosBD: comboInterface[] = [
  {
    estrellas: 5,
    existentes: 20,
    img: '/assets/images/cards/comboBurguerPapas.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'nombre combo 1',
    peso: '1 KG',
    precio: '$15.000',
    REF: '#654vev3',
  },
  {
    estrellas: 5,
    existentes: 10,
    img: '/assets/images/cards/superBurguer.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'nombre combo 2',
    precio: '$20.000',
    peso: '1.5 KG',
    REF: '#654vev2',
  },
  {
    estrellas: 5,
    existentes: 15,
    img: '/assets/images/cards/comboHotDogs.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'nombre combo 3',
    precio: '$15.000',
    peso: '1 KG',
    REF: '#654vev1',
  },
  {
    estrellas: 4,
    existentes: 0,
    img: '/assets/images/cards/burguerChicken.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Burguer Chicken',
    peso: 'string',
    precio: '$13.450',
    REF: '#54m4652n1',
  },
  {
    estrellas: 3,
    existentes: 0,
    img: '/assets/images/cards/burguersPapas.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Doble carne y papas',
    peso: 'string',
    precio: '$23.450',
    REF: '#54m4652n2',
  },
  {
    estrellas: 3,
    existentes: 0,
    img: '/assets/images/cards/lunchPolloPapas.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Blunch Pollo Papas',
    peso: 'string',
    precio: '$10.450',
    REF: '#54m4652n3',
  },
  {
    estrellas: 4,
    existentes: 0,
    img: '/assets/images/cards/polloNaranja.png',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Pollo Naranja',
    peso: 'string',
    precio: '$25.650',
    REF: '#54m4652n4',
  },
  {
    estrellas: 3,
    existentes: 0,
    img: '/assets/images/cards/sachipapa1.png',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Sachipapa',
    peso: 'string',
    precio: '$8.350',
    REF: '#54m4652n5',
  },
  {
    estrellas: 4,
    existentes: 0,
    img: '/assets/images/cards/salchipapaCilantro.png',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Salchipapa Cilantro',
    peso: 'string',
    precio: '$8.350',
    REF: '#54m4652n6',
  },
  {
    estrellas: 3,
    existentes: 0,
    img: '/assets/images/cards/nuggetsPapas.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Nuggets Papas',
    peso: 'string',
    precio: '$14.990',
    REF: '#54m4652n7',
  },
  {
    estrellas: 4,
    existentes: 0,
    img: '/assets/images/cards/carneAsada.jpg',
    incluye: 'papas gaseosa',
    ingredientes: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit.',
    nombre: 'Carne Asada',
    peso: 'string',
    precio: '$28.790',
    REF: '#54m4652n8',
  },
];
